headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/goat/chalet-beyond/dist/public"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm build"

[build.environment]
NODE_VERSION = "20"
PNPM_VERSION = "10"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/videos/*"

[headers.values]
Cache-Control = "public, max-age=2592000"
Accept-Ranges = "bytes"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]