import type { Lang } from "@shared/i18n";
import { LONG_STAY_DISCOUNT_RATE, LONG_STAY_MIN_NIGHTS } from "@shared/pricing";
import { useLang } from "@/i18n/LanguageProvider";

const longStayPercent = Math.round(LONG_STAY_DISCOUNT_RATE * 100);

const sk = {
  intro: ["250 m² len", "pre vašu partiu."],
  facts: [
    ["Golf", "Black Stork vo Veľkej Lomnici."],
    ["Súkromné wellness", "Sauna a vírivka patria iba vášmu pobytu."],
    ["Vysoké Tatry", "Hory, ktoré vidíte aj z obývačky."],
  ],
  gallery: ["Dom, ktorý", "chcete spoznať."],
  albums: ["Exteriér", "Interiér", "Spálne", "Wellness", "Okolie"],
  albumFacts: [
    "Drevo, záhrada a terasa",
    "Obývačka s kozubom",
    "Tri spálne",
    "Súkromná sauna a vírivka",
    "Veľká Lomnica, Vysoké Tatry",
  ],
  photoAlt: [
    "Chalet a jeho záhrada",
    "Drevená architektúra chaletu",
    "Výhľad na Tatry ponad lúku",
    "Krytá terasa",
    "Vonkajšia vírivka pri chate",
    "Vírivka v drevenom ráme pred chatou",
    "Chalet zo záhrady",
    "Obývačka s kozubom a oknami do záhrady",
    "Ležadlo pri kozube",
    "Oddych pri veľkom okne",
    "Kuchynské spotrebiče",
    "Spálňa s dreveným stropom",
    "Spálňa s výhľadom do záhrady",
    "Drevená súkromná sauna",
    "Spálňa s kreslami a veľkým oknom",
    "Kúpeľňa so sprchou",
    "Dvojité umývadlo v kúpeľni",
    "Otvorená kuchyňa s jedálenským stolom",
    "Jedálenský stôl pri oknách",
    "Vybavená kuchyňa",
    "Jedáleň a terasa cez sklo",
  ],
  interlude: ["Ranná káva.", "Tatry za oknom."],
  amenities: ["Večer patrí", "iba vám."],
  amenitiesBody: "Teplo dreva, pokoj a priestor na spoločný čas.",
  featured: ["Sauna", "Vírivka", "Kozub"],
  location: ["Hory na dosah.", "Domov v Lomnici."],
  locationBody:
    "Chalet Beyond vo Veľkej Lomnici je základňa na objavovanie Vysokých Tatier.",
  places: [
    ["Black Stork", "Golf vo Veľkej Lomnici"],
    ["Tatranská Lomnica", "Hory, turistika a lyžovanie"],
    ["AquaCity Poprad", "Vodný oddych"],
    ["Poprad–Tatry", "Letisko v regióne"],
  ],
  map: "Otvoriť mapu",
  pricing: ["Celý chalet.", "Vaša priama cena."],
  from: "od",
  night: "/ noc",
  whole: "Celý chalet pre vašu skupinu",
  baseNight: "Základná cena za noc",
  weeklyNote: `Pri pobyte na ${LONG_STAY_MIN_NIGHTS} a viac nocí zľava ${longStayPercent} % z celého pobytu.`,
  rateNote:
    "Tabuľka uvádza základné ceny za noc pre dospelých. Cena za zvolený termín vrátane zliav sa zobrazí pri rezervácii.",
  allPrices: "Zobraziť všetky ceny",
  adults: "Dospelí (16+)",
  children: "Deti (0–15)",
  childNote: "Deti 0–15 rokov: 40 € / noc za dieťa. Spolu najviac 8 hostí.",
  booking: ["Overte", "voľný termín."],
  bookingBody: "Vyberte dátumy a pošlite dopyt priamo majiteľovi.",
  continue: "Pokračovať",
  edit: "Upraviť termín",
  optional: "voliteľné",
  dateError: "Vyberte príchod a odchod, minimálne 2 noci.",
  datesBusy: "Tento rozsah obsahuje obsadené noci. Vyberte iný odchod.",
  assurances: "Bezplatné storno do 14 dní pred príchodom · Min. 2 noci",
  successBody:
    "Dopyt sme prijali. Ozveme sa vám s potvrdením dostupnosti a ďalším postupom.",
  successEmail: "Potvrdenie prijatia sme poslali na",
  summary: "Váš pobyt",
  baseStay: "Základná cena pobytu",
  weeklySaving: `Zľava za ${LONG_STAY_MIN_NIGHTS}+ nocí (${longStayPercent} %)`,
  promotionSaving: "Termínová zľava",
  total: "Spolu za pobyt",
  nights: "Počet nocí",
  bar: "Termín · od {price} €",
  close: "Zavrieť galériu",
  previous: "Predchádzajúca fotka",
  next: "Nasledujúca fotka",
  photo: "Fotka",
  notFound: "Táto stránka tu nie je.",
  home: "Späť na úvod",
};
type Copy = { [K in keyof typeof sk]: (typeof sk)[K] };
const de: Copy = {
  intro: ["250 m² nur", "für Ihre Runde."],
  facts: [
    ["Golf", "Black Stork in Veľká Lomnica."],
    ["Privates Wellness", "Sauna und Whirlpool nur für Ihren Aufenthalt."],
    ["Hohe Tatra", "Bergblick direkt vom Wohnzimmer."],
  ],
  gallery: ["Ein Haus zum", "Kennenlernen."],
  albums: [
    "Außenbereich",
    "Innenräume",
    "Schlafzimmer",
    "Wellness",
    "Umgebung",
  ],
  albumFacts: [
    "Holz, Garten und Terrasse",
    "Wohnzimmer mit Kamin",
    "Drei Schlafzimmer",
    "Private Sauna und Whirlpool",
    "Veľká Lomnica, Hohe Tatra",
  ],
  photoAlt: [
    "Chalet und Garten",
    "Holzarchitektur des Chalets",
    "Tatrablick über die Wiese",
    "Überdachte Terrasse",
    "Whirlpool im Freien am Chalet",
    "Whirlpool mit Holzumrandung vor dem Chalet",
    "Chalet vom Garten aus",
    "Wohnzimmer mit Kamin und Gartenfenstern",
    "Liege am Kamin",
    "Ruheplatz am großen Fenster",
    "Küchengeräte",
    "Schlafzimmer mit Holzdecke",
    "Schlafzimmer mit Gartenblick",
    "Private Holzsauna",
    "Schlafzimmer mit Sesseln und großem Fenster",
    "Badezimmer mit Dusche",
    "Doppelwaschbecken im Badezimmer",
    "Offene Küche mit Esstisch",
    "Esstisch am Fenster",
    "Ausgestattete Küche",
    "Essbereich und Terrasse hinter Glas",
  ],
  interlude: ["Morgenkaffee.", "Tatra vor dem Fenster."],
  amenities: ["Der Abend", "gehört Ihnen."],
  amenitiesBody: "Warmes Holz, Ruhe und Raum für gemeinsame Zeit.",
  featured: ["Sauna", "Whirlpool", "Kamin"],
  location: ["Berge in Reichweite.", "Zuhause in Lomnica."],
  locationBody:
    "Chalet Beyond in Veľká Lomnica ist Ihr Ausgangspunkt für die Hohe Tatra.",
  places: [
    ["Black Stork", "Golf in Veľká Lomnica"],
    ["Tatranská Lomnica", "Berge, Wandern und Skifahren"],
    ["AquaCity Poprad", "Wasser und Erholung"],
    ["Poprad–Tatry", "Flughafen in der Region"],
  ],
  map: "Karte öffnen",
  pricing: ["Das ganze Chalet.", "Ihr direkter Preis."],
  from: "ab",
  night: "/ Nacht",
  whole: "Das ganze Chalet für Ihre Gruppe",
  baseNight: "Grundpreis pro Nacht",
  weeklyNote: `Ab ${LONG_STAY_MIN_NIGHTS} Nächten: ${longStayPercent} % Rabatt auf den gesamten Aufenthalt.`,
  rateNote:
    "Die Tabelle zeigt Grundpreise pro Nacht für Erwachsene. Der Preis für Ihre Daten einschließlich Rabatten erscheint bei der Buchungsanfrage.",
  allPrices: "Alle Preise anzeigen",
  adults: "Erwachsene (16+)",
  children: "Kinder (0–15)",
  childNote:
    "Kinder 0–15 Jahre: 40 € / Nacht pro Kind. Insgesamt höchstens 8 Gäste.",
  booking: ["Freie Termine", "prüfen."],
  bookingBody:
    "Wählen Sie Ihren Aufenthalt und fragen Sie direkt beim Eigentümer an.",
  continue: "Weiter",
  edit: "Termin ändern",
  optional: "optional",
  dateError: "Wählen Sie An- und Abreise, mindestens 2 Nächte.",
  datesBusy:
    "Dieser Zeitraum enthält belegte Nächte. Wählen Sie eine andere Abreise.",
  assurances: "Kostenlos stornieren bis 14 Tage vor Anreise · Min. 2 Nächte",
  successBody:
    "Ihre Anfrage ist eingegangen. Wir melden uns mit Verfügbarkeit und den nächsten Schritten.",
  successEmail: "Die Eingangsbestätigung wurde gesendet an",
  summary: "Ihr Aufenthalt",
  baseStay: "Grundpreis des Aufenthalts",
  weeklySaving: `Rabatt ab ${LONG_STAY_MIN_NIGHTS} Nächten (${longStayPercent} %)`,
  promotionSaving: "Zeitraumangebot",
  total: "Gesamtpreis",
  nights: "Nächte",
  bar: "Termin · ab {price} €",
  close: "Galerie schließen",
  previous: "Vorheriges Foto",
  next: "Nächstes Foto",
  photo: "Foto",
  notFound: "Diese Seite gibt es nicht.",
  home: "Zur Startseite",
};
const en: Copy = {
  intro: ["250 m², entirely", "for your group."],
  facts: [
    ["Golf", "Black Stork in Veľká Lomnica."],
    ["Private wellness", "Sauna and hot tub exclusively for your stay."],
    ["High Tatras", "Mountain views from the living room."],
  ],
  gallery: ["A house worth", "getting to know."],
  albums: ["Exterior", "Interior", "Bedrooms", "Wellness", "Surroundings"],
  albumFacts: [
    "Timber, garden and terrace",
    "Living room with fireplace",
    "Three bedrooms",
    "Private sauna and hot tub",
    "Veľká Lomnica, High Tatras",
  ],
  photoAlt: [
    "Chalet and garden",
    "Timber chalet architecture",
    "Tatra view across the meadow",
    "Covered terrace",
    "Outdoor hot tub beside the chalet",
    "Hot tub in a timber surround by the chalet",
    "Chalet seen from the garden",
    "Living room with fireplace and garden windows",
    "Lounge chair by the fireplace",
    "Resting area by a large window",
    "Kitchen appliances",
    "Bedroom with timber ceiling",
    "Bedroom overlooking the garden",
    "Private timber sauna",
    "Bedroom with armchairs and large window",
    "Bathroom with shower",
    "Double bathroom basin",
    "Open kitchen with dining table",
    "Dining table beside windows",
    "Equipped kitchen",
    "Dining area and terrace through glass",
  ],
  interlude: ["Morning coffee.", "Tatras at the window."],
  amenities: ["The evening", "is yours."],
  amenitiesBody: "Warm timber, quiet and room for time together.",
  featured: ["Sauna", "Hot tub", "Fireplace"],
  location: ["Mountains within reach.", "Home in Lomnica."],
  locationBody:
    "Chalet Beyond in Veľká Lomnica is your base for exploring the High Tatras.",
  places: [
    ["Black Stork", "Golf in Veľká Lomnica"],
    ["Tatranská Lomnica", "Mountains, hiking and skiing"],
    ["AquaCity Poprad", "Water and relaxation"],
    ["Poprad–Tatry", "Regional airport"],
  ],
  map: "Open map",
  pricing: ["The whole chalet.", "Your direct price."],
  from: "from",
  night: "/ night",
  whole: "The whole chalet for your group",
  baseNight: "Base price per night",
  weeklyNote: `Stay ${LONG_STAY_MIN_NIGHTS} nights or more: ${longStayPercent}% off the entire stay.`,
  rateNote:
    "The table shows adult base rates per night. Your date-specific price, including any discount, appears in the booking summary.",
  allPrices: "Show all prices",
  adults: "Adults (16+)",
  children: "Children (0–15)",
  childNote:
    "Children aged 0–15: €40 / night per child. Maximum 8 guests in total.",
  booking: ["Check available", "dates."],
  bookingBody: "Choose your dates and send an inquiry directly to the owner.",
  continue: "Continue",
  edit: "Edit dates",
  optional: "optional",
  dateError: "Choose arrival and departure, at least 2 nights.",
  datesBusy: "This range includes occupied nights. Choose another departure.",
  assurances: "Free cancellation until 14 days before arrival · Min. 2 nights",
  successBody:
    "We received your inquiry. We will contact you with availability and the next steps.",
  successEmail: "An acknowledgment was sent to",
  summary: "Your stay",
  baseStay: "Base stay price",
  weeklySaving: `${LONG_STAY_MIN_NIGHTS}+ night discount (${longStayPercent}%)`,
  promotionSaving: "Dated offer",
  total: "Total for your stay",
  nights: "Nights",
  bar: "Dates · from €{price}",
  close: "Close gallery",
  previous: "Previous photo",
  next: "Next photo",
  photo: "Photo",
  notFound: "This page is not here.",
  home: "Back to home",
};
const pl: Copy = {
  intro: ["250 m² tylko", "dla Was."],
  facts: [
    ["Golf", "Black Stork w Veľkiej Lomnicy."],
    ["Prywatne wellness", "Sauna i jacuzzi tylko na Wasz pobyt."],
    ["Tatry Wysokie", "Widok na góry prosto z salonu."],
  ],
  gallery: ["Dom, który", "warto poznać."],
  albums: ["Na zewnątrz", "Wnętrza", "Sypialnie", "Wellness", "Okolica"],
  albumFacts: [
    "Drewno, ogród i taras",
    "Salon z kominkiem",
    "Trzy sypialnie",
    "Prywatna sauna i jacuzzi",
    "Veľká Lomnica, Tatry Wysokie",
  ],
  photoAlt: [
    "Chalet i ogród",
    "Drewniana architektura chaletu",
    "Widok na Tatry ponad łąką",
    "Zadaszony taras",
    "Jacuzzi na zewnątrz przy chalecie",
    "Jacuzzi w drewnianej obudowie przy chalecie",
    "Chalet od strony ogrodu",
    "Salon z kominkiem i oknami na ogród",
    "Leżanka przy kominku",
    "Miejsce odpoczynku przy dużym oknie",
    "Sprzęt kuchenny",
    "Sypialnia z drewnianym sufitem",
    "Sypialnia z widokiem na ogród",
    "Prywatna drewniana sauna",
    "Sypialnia z fotelami i dużym oknem",
    "Łazienka z prysznicem",
    "Podwójna umywalka w łazience",
    "Otwarta kuchnia ze stołem",
    "Stół jadalny przy oknach",
    "Wyposażona kuchnia",
    "Jadalnia i taras za szkłem",
  ],
  interlude: ["Poranna kawa.", "Tatry za oknem."],
  amenities: ["Wieczór należy", "tylko do Was."],
  amenitiesBody: "Ciepło drewna, spokój i przestrzeń na wspólny czas.",
  featured: ["Sauna", "Jacuzzi", "Kominek"],
  location: ["Góry w zasięgu.", "Dom w Lomnicy."],
  locationBody:
    "Chalet Beyond w Veľkiej Lomnicy to baza do odkrywania Tatr Wysokich.",
  places: [
    ["Black Stork", "Golf w Veľkiej Lomnicy"],
    ["Tatranská Lomnica", "Góry, wędrówki i narty"],
    ["AquaCity Poprad", "Wodny wypoczynek"],
    ["Poprad–Tatry", "Lotnisko w regionie"],
  ],
  map: "Otwórz mapę",
  pricing: ["Cały chalet.", "Wasza cena bezpośrednia."],
  from: "od",
  night: "/ noc",
  whole: "Cały chalet dla Waszej grupy",
  baseNight: "Cena podstawowa za noc",
  weeklyNote: `Przy pobycie na co najmniej ${LONG_STAY_MIN_NIGHTS} nocy: ${longStayPercent}% zniżki na cały pobyt.`,
  rateNote:
    "Tabela pokazuje podstawowe ceny za noc dla dorosłych. Cena dla wybranego terminu wraz ze zniżką pojawi się w podsumowaniu rezerwacji.",
  allPrices: "Pokaż wszystkie ceny",
  adults: "Dorośli (16+)",
  children: "Dzieci (0–15)",
  childNote:
    "Dzieci 0–15 lat: 40 € / noc za dziecko. Łącznie maksymalnie 8 gości.",
  booking: ["Sprawdźcie", "wolny termin."],
  bookingBody:
    "Wybierzcie daty i wyślijcie zapytanie bezpośrednio właścicielowi.",
  continue: "Dalej",
  edit: "Zmień termin",
  optional: "opcjonalne",
  dateError: "Wybierzcie przyjazd i wyjazd, minimum 2 noce.",
  datesBusy: "Ten zakres obejmuje zajęte noce. Wybierzcie inną datę wyjazdu.",
  assurances: "Bezpłatne anulowanie do 14 dni przed przyjazdem · Min. 2 noce",
  successBody:
    "Otrzymaliśmy zapytanie. Skontaktujemy się z Wami z dostępnością i kolejnymi krokami.",
  successEmail: "Potwierdzenie otrzymania wysłaliśmy na",
  summary: "Wasz pobyt",
  baseStay: "Podstawowa cena pobytu",
  weeklySaving: `Zniżka za ${LONG_STAY_MIN_NIGHTS}+ nocy (${longStayPercent}%)`,
  promotionSaving: "Oferta terminowa",
  total: "Łącznie za pobyt",
  nights: "Liczba nocy",
  bar: "Termin · od {price} €",
  close: "Zamknij galerię",
  previous: "Poprzednie zdjęcie",
  next: "Następne zdjęcie",
  photo: "Zdjęcie",
  notFound: "Tej strony tutaj nie ma.",
  home: "Powrót na początek",
};
export const premiumCopy: Record<Lang, Copy> = { sk, de, en, pl };
export function usePremiumCopy() {
  return premiumCopy[useLang()];
}
export const PHOTO_IDS = [
  2, 3, 12, 28, 31, 33, 38, 43, 44, 46, 48, 54, 55, 58, 60, 62, 63, 65, 68, 70,
  72,
];
